dist: trusty
sudo: false

language: python
python:
  - 3.6

install:
  - pip install pycurl

git:
  depth: 1

addons:
  apt:
    packages:
      - p7zip-full

script:
  - export PYTHON_VERSION=3.9.9
  - export PYTHON_IMPL_VERSION=cp39
  - export RELEASE_VERSION=$(grep -oP '[0-9\.ab]+' local/__init__.py)
  - export CA_MOZILLA=cert/cacerts/mozilla.pem
  - export CA_GOOGLE=cert/cacerts/google.pem

before_deploy:
  - curl -L --cacert ${CA_MOZILLA} -o ${CA_MOZILLA} https://curl.se/ca/cacert.pem
  - curl -L --cacert ${CA_GOOGLE} -o ${CA_GOOGLE} https://pki.goog/roots.pem
  - python launcher/buildipdb.py -u -d --17mon
  - python launcher/builddomains.py -u -d --felix

  - cd python/site-packages
  - 7z a -tzip -mx=9 -mfb=258 -mtc=off helpers-win32.egg winsystray
  - rm -rf winsystray
  - cd ../..

  - rm -rf .git*
  - rm -rf .travis*

  - 7z a -mx=9 -mfb=258 -mtc=off GotoX-${RELEASE_VERSION}-py3-any.zip *
  - mv *.zip ..
  - cd ..

  - pack() {
    cp -r GotoX GotoX-${3};
    cd GotoX-${3};
    python pack_portable.py ${1}-${3};
    rm -rf pack_portable.*;
    7z a -mx=9 -m0=BCJ2 -m1=LZMA2:mf=bt3 -m2=LZMA:d19 -m3=LZMA:d19 -m4=LZMA:d19
    -mb0s0:1 -mb0s1:2 -mb0s2:3 -mb0s3:4 GotoX-${RELEASE_VERSION}-${2}-${3}.7z *;
    mv *.7z ..;
    cd ..;
    }

  - pack ${PYTHON_VERSION} ${PYTHON_IMPL_VERSION} win32
  - pack ${PYTHON_VERSION} ${PYTHON_IMPL_VERSION} win_amd64

  - md5sum *.zip *.7z | tee md5sum
  - sha256sum *.zip *.7z | tee sha256sum

deploy:
  provider: releases
  api_key: ${DEPLOY_TOKEN}
  file_glob: true
  file: 
    - "*.zip"
    - "*.7z"
    - "*sum"
  skip_cleanup: true
  draft: true
  on:
    tags: true
    repo: SeaHOH/GotoX

notifications:
  email: false
